
spring:
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/atom_test_db
    username: atom_test_db_use
    password: y1jX8eKH7n5PX8ED
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
logging:
  level:
    root: debug
