apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-data-jpa-demo-configmap
data:
  # file format
  application.yml: |
    spring:
      datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
    server:
      port: 8080
    logging:
      level:
        root: debug
