apiVersion: v1
kind: Secret
metadata:
  name: spring-data-jpa-demo-datasource-credentials
type: Opaque
data:
  "spring.datasource.url": "amRiYzpteXNxbDovL215c3FsLnNxbHB1Yi5jb206MzMwNi9hdG9tX3Rlc3RfZGI="
  "spring.datasource.username": "YXRvbV90ZXN0X2RiX3VzZQ=="
  "spring.datasource.password": "eTFqWDhlS0g3bjVQWDhFRA=="

